export const STATUS_CODE_SUCCESS = 200
export const STATUS_CODE_BAD_REQUEST = 400
export const STATUS_CODE_UNAUTHORIZED = 401
export const STATUS_CODE_FORBIDDEN = 403
export const STATUS_CODE_NOT_FOUND = 404
export const STATUS_CODE_VALIDATE_ERROR = 422
export const STATUS_CODE_SERVER_ERROR = 500
export const HTTP_TOO_MANY_REQUESTS = 429
